/**:
  ros__parameters:
    model:
      mass: 14.5
      inertia:
      - 0.25
      - 0.25
      - 0.4
      cog:
      - 0.0
      - 0.0
      - 0.0
      added_mass:
      - 15.0
      - 21.0
      - 27.0
      - 0.22499999999999998
      - 0.22499999999999998
      - 0.30000000000000004
      buoyancy: 14.45
      cob:
      - 0.0
      - 0.0
      - 0.31
      damping_linear:
      - 10.0
      - 12.0
      - 15.0
      - 0.5
      - 0.5
      - 0.5
      damping_nonlinear:
      - 40.0
      - 40.0
      - 80.0
      - 1.0
      - 1.0
      - 1.5
    manipulator_comp:
      origin:
        x: 0.086
        y: 0.0
        z: -0.109
      buoyancy_mass: 0.899
